version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    ports:
      - "8001:8000"       # mapeia porta do Artisan Serve
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:CHANGE_ME_LATER
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_api
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db
    # Usaremos o servidor embutido do Laravel
    command: ["php","artisan","serve","--host=0.0.0.0","--port=8000"]

    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html

  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel_api
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
